app:
    resource: '@AppBundle/Controller/'
    type: annotation

homepage:
    path:   /
    defaults:  { _controller: AppBundle:Default:index}

ConnexionEleve:
    path: /Accueil
    defaults: {_controller: AppBundle:ConnexionUtilisateur:connexionEleve}

ConnexionPeda:
    path: /Accueil
    defaults: {_controller: AppBundle:ConnexionUtilisateur:connexionInterPeda}